require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CardPacksController do

  # This should return the minimal set of attributes required to create a valid
  # CardPack. As you add validations to CardPack, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CardPacksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all card_packs as @card_packs" do
      card_pack = CardPack.create! valid_attributes
      get :index, {}, valid_session
      assigns(:card_packs).should eq([card_pack])
    end
  end

  describe "GET show" do
    it "assigns the requested card_pack as @card_pack" do
      card_pack = CardPack.create! valid_attributes
      get :show, {:id => card_pack.to_param}, valid_session
      assigns(:card_pack).should eq(card_pack)
    end
  end

  describe "GET new" do
    it "assigns a new card_pack as @card_pack" do
      get :new, {}, valid_session
      assigns(:card_pack).should be_a_new(CardPack)
    end
  end

  describe "GET edit" do
    it "assigns the requested card_pack as @card_pack" do
      card_pack = CardPack.create! valid_attributes
      get :edit, {:id => card_pack.to_param}, valid_session
      assigns(:card_pack).should eq(card_pack)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CardPack" do
        expect {
          post :create, {:card_pack => valid_attributes}, valid_session
        }.to change(CardPack, :count).by(1)
      end

      it "assigns a newly created card_pack as @card_pack" do
        post :create, {:card_pack => valid_attributes}, valid_session
        assigns(:card_pack).should be_a(CardPack)
        assigns(:card_pack).should be_persisted
      end

      it "redirects to the created card_pack" do
        post :create, {:card_pack => valid_attributes}, valid_session
        response.should redirect_to(CardPack.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved card_pack as @card_pack" do
        # Trigger the behavior that occurs when invalid params are submitted
        CardPack.any_instance.stub(:save).and_return(false)
        post :create, {:card_pack => {}}, valid_session
        assigns(:card_pack).should be_a_new(CardPack)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CardPack.any_instance.stub(:save).and_return(false)
        post :create, {:card_pack => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested card_pack" do
        card_pack = CardPack.create! valid_attributes
        # Assuming there are no other card_packs in the database, this
        # specifies that the CardPack created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CardPack.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => card_pack.to_param, :card_pack => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested card_pack as @card_pack" do
        card_pack = CardPack.create! valid_attributes
        put :update, {:id => card_pack.to_param, :card_pack => valid_attributes}, valid_session
        assigns(:card_pack).should eq(card_pack)
      end

      it "redirects to the card_pack" do
        card_pack = CardPack.create! valid_attributes
        put :update, {:id => card_pack.to_param, :card_pack => valid_attributes}, valid_session
        response.should redirect_to(card_pack)
      end
    end

    describe "with invalid params" do
      it "assigns the card_pack as @card_pack" do
        card_pack = CardPack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CardPack.any_instance.stub(:save).and_return(false)
        put :update, {:id => card_pack.to_param, :card_pack => {}}, valid_session
        assigns(:card_pack).should eq(card_pack)
      end

      it "re-renders the 'edit' template" do
        card_pack = CardPack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CardPack.any_instance.stub(:save).and_return(false)
        put :update, {:id => card_pack.to_param, :card_pack => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested card_pack" do
      card_pack = CardPack.create! valid_attributes
      expect {
        delete :destroy, {:id => card_pack.to_param}, valid_session
      }.to change(CardPack, :count).by(-1)
    end

    it "redirects to the card_packs list" do
      card_pack = CardPack.create! valid_attributes
      delete :destroy, {:id => card_pack.to_param}, valid_session
      response.should redirect_to(card_packs_url)
    end
  end

end
